spring:
  profiles:
    include: jwt, local
  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  config: classpath:logback.xml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

