spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sff-owner
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  profiles:
    include: jwt

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

