spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_ID}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  config: classpath:logback.xml
  level:
    root: info
server:
  port: 8110
eureka:
  instance:
    prefer-ip-address: true
    ip-address: k9e205.p.ssafy.io
    non-secure-port: 8110
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@k9e205.p.ssafy.io:8761/eureka/

feign:
  storeserver:
    url: k9e205.p.ssafy.io:8090
  userserver:
    url: k9e205.p.ssafy.io:8100
  payserver:
    url: k9e205.p.ssafy.io:8110
  notiserver:
    url: k9e205.p.ssafy.io:8120
  orderserver:
    url: k9e205.p.ssafy.io:8130
  ownerserver:
    url: k9e205.p.ssafy.io:8140