server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  data:
    User_Server: "http://k9e205.p.ssafy.io:8100"
    Order_Server: "http://localhost:8080" #http://k9e205.p.ssafy.io:8130
    Store_Server: "http://k9e205.p.ssafy.io:8090"
    Owner_Server: "http://k9e205.p.ssafy.io:8140"